### ISSUE TITLE
Crystals do not break when ore block removed + related crash-to-desktop

### ISSUE THREAD

**Issue by nicwatson** [TaskaRaine/Ore-Crystals#7]
As of v1.3.3, when mining an ore block that has attached crystals, the crystals do not automatically break and fall off. They remain floating in mid-air. They can be broken manually. I can reproduce this consistently, and with no other mods installed.

Additionally, there seems to be a fatal crash associated with these circumstances, though it is less consistent -- I can reproduce it semi-reliably if I mine enough ores without manually breaking crystals. It seems to be that if enough crystals are left floating (or perhaps just crystals left in the right locations), attempting to mine out another nearby block will crash the game. This is an instant freeze of several seconds, followed by the program terminating abruptly. Unfortunately, it does not provide an error report/stacktrace and does not dump any relevant information whatsoever to any of the log files (latest timestamps are at least a couple minutes before I even began mining).

(The first attached image shows floating crystals. The second was taken immediately after punching out a block, leaving three floating crystal clusters behind. The quartz block under the crosshairs was punched next, triggering an instant crash.)

Rolling back to v1.3.2 resolves both problems.
Hope this helps, and thanks for your work on this mod!

![2021-08-12_19-27-44](https://user-images.githubusercontent.com/587252/129283430-bf4bd37a-6bf1-4a89-a940-4ef746420127.jpg)
![2021-08-12_19-28-41](https://user-images.githubusercontent.com/587252/129283429-f3624df8-c886-45a4-8ace-f95ccd7abd38.jpg)

**Comment by TaskaRaine** [comment]
I actually just dug into this....and realized I'd removed a line of code that I shouldn't have. My oops... sorry for the inconvenience @_@

There's a fix for it on the ModDb here: https://mods.vintagestory.at/show/mod/73

**Comment by TaskaRaine** [comment]
Thanks for the report and such a detailed explanation of what was happening!
